#!/usr/bin/env ansible-playbook
---
- name: caching DNS setup
  hosts: pladd-laptop.usersys.redhat.com

  tasks:
    - name: dnsmasq package
      package: name={{ item }} state=latest
      with_items:
      - dnsmasq

    - name: NetworkManager config
      lineinfile:
        path: /etc/NetworkManager/NetworkManager.conf
        insertafter: '^\[main\]'
        regex: '^dns='
        line: 'dns=dnsmasq'
      notify:
        - reload NetworkManager

  # Might need https://fedoramagazine.org/using-the-networkmanagers-dnsmasq-plugin/ in the future

  handlers:
    - name: reload NetworkManager
      service:
        name: NetworkManager
        state: reloaded
...
