#!/usr/bin/env ansible-playbook
---
- name: git install
  hosts: all

  tasks:
  - name: git_package
    package: name={{ item }} state=latest
    with_items:
      - git

  - name: git_gui
    package: name={{ item }} state=latest
    with_items:
      - git-cola
    when: "'desktops' in group_names"

  - git_config:
      name: init.defaultBranch
      value: main
      scope: system

  - git_config:
      name: core.editor
      value: vim
      scope: system

  - git_config:
      name: user.name
      value: Patrick Ladd
      scope: global
    become_user: pladd
    become: true
    when: "'desktops' in group_names"

  - git_config:
      name: user.email
      value: pladd@redhat.com
      scope: global
    become_user: pladd
    become: true
    when: "'desktops' in group_names"
...
