#!/usr/bin/env ansible-playbook
---
- hosts: desktops
  tasks:

  - name: package
    dnf:
      name:
      - cmake
      - extra-cmake-modules
      - libfreecell-solver
      - libfreecell-solver-devel
      state: latest

...
