#!/usr/bin/env ansible-playbook
---
- name: test_leapp
  hosts: rhel78
  vars:
    vg: rhel_rhel78
    root: root
    rollback: rollback

  tasks:
  - name: packages
    yum:
      name:
        - leapp
        - leapp-repository
        - leapp-repository-deps
        - lvm2-python-boom
        - cockpit-leapp
      state: latest

  - name: rollback_lv
    lvol:
      vg: "{{ vg }}"
      lv: "{{ root }}"
      snapshot: "{{ rollback }}"
      size: 10g

  - name: boom_list
    command: "boom list -L {{ vg }}/{{ rollback }} -o rootdev --noheadings"
    register: boom

  - name: boom
    command: "boom create --title 'RHEL snapshot' --rootlv {{ vg }}/{{ rollback }}"
    register: boom
    when: "boom.stdout|length == 0"
  - debug:
      var: boom

  - name: grub
    shell: "grub2-mkconfig > /boot/grub2/grub.cfg"
    register: grub
  - debug:
      var: grub

  - name: copy_leapp_data
    unarchive:
      dest: /etc/leapp/files
      src: leapp-data7.tar.gz

  - name: firewalld
    firewalld:
      service: cockpit
      state: enabled
      permanent: yes
      immediate: yes

  - name: cockpit service socket
    service:
      name: cockpit.socket
      state: started
      enabled: true

  - name: leapp_eval
    command: "leapp preupgrade"
    register: leapp
  - debug:
      var: leapp

  - name: leapp_doit
    command: "leapp upgrade --debug"
    register: leapp
  - debug:
      var: leapp

  - name: reboot
    reboot:
      reboot_timeout: 3600

  - name: delete_snapshot
    lvol:
      vg: "{{ vg }}"
      lv: "{{ rollback }}"
      state: absent

  - name: rollback_to_snapshot
    command: "lvconvert --merge /dev/{{ vg }}/{{ rollback }}"
    register: rollback
  - debug:
      var: rollback

...
