#!/usr/bin/env ansible-playbook
---
- hosts: all

  tasks:
  - name: network packages
    package: name={{ item }} state=latest
    with_items:
    - nmap
    - tcpdump
    - traceroute
    - wireshark
    - bind-utils # for dig
    - ntop

- hosts: desktops

  tasks:
  - name: network GUI packages
    package: name={{ item }} state=latest
    with_items:
    - nmap-frontend
    - wireshark-gnome
    - firewall-config
...