---
- name: required network packages
  hosts: beast
  tasks:
  - name: install needed network packages
    yum:
      state: latest
      name:
      - rhel-system-roles
      - dbus
      - NetworkManager
      - NetworkManager-libnm

- name: Settings for beast server
  hosts: beast
  vars:
    network_connections:
      - name: enp65s1
        type: ethernet
        ip:
          address: 192.168.42.200
          dns: "8.8.8.8,8.8.4.4"
          route:
            network: 0.0.0.0
            gateway: 192.168.42.1
            metric:  300

      - name: beast-team
        type: team
        state: up
        mode: balance-rr
        ip:
          dhcp4: yes

      - name: beast-t1
        type: team-slave
        master: beast-team
        interface-name: enp65s2

      - name: beast-t2
        type: team-slave
        master: beast-team
        interface-name: ens6f0

      - name: beast-t3
        type: team-slave
        master: beast-team
        interface-name: ens6f1

#  roles:
#  - role: rhel-system-roles.network

  tasks:
  - name: adjust metrics to prefer team interface
    command: nmcli connection modify beast-team ipv4.route-metric 100

  - name: adjust metrics to prefer team interface
    command: nmcli connection modify enp65s1 ipv4.route-metric 300

...
