#!/usr/bin/env ansible-playbook
---
- hosts: all

  tasks:
  - name: network packages
    package:
      state: latest
      name:
      - nmap
      - tcpdump
      - traceroute
      - wireshark-cli
      - bind-utils # for dig

  - name: network GUI packages
    package:
      state: latest
      name:
      - wireshark
      - firewall-config
    when: "'desktops' in group_names"
  ...
