#!/usr/bin/env ansible-playbook
---
- name: Settings for ogre server
  hosts: ogre
  vars:
    network_connections:
      - name: eno4
        type: ethernet
        interface_name: eno4
        ip:
          address:
            - 192.168.42.211/24
          dns:
            - "192.168.42.59"
            - "192.168.42.1"
            - "8.8.8.8"
          dns_search:
            - home.pladd.net
          route_metric4: 300
          gateway4: 192.168.42.1
        autoconnect: false

      - name: enp65s0f1
        type: ethernet
        interface_name: enp65s0f1
        ip:
          address:
            - 192.168.42.212/24
          dns:
            - "192.168.42.59"
            - "192.168.42.1"
            - "8.8.8.8"
          dns_search:
            - home.pladd.net
          route_metric4: 300
          gateway4: 192.168.42.1
        autoconnect: false

      - name: bond0
        type: bond
        bond:
          mode: 802.3ad
        ip:
          address:
            - 192.168.42.210/24
          dns:
            - "192.168.42.59"
            - "192.168.42.1"
            - "8.8.8.8"
          dns_search:
            - home.pladd.net
          route_metric4: 1
          gateway4: 192.168.42.1
          auto6: false

      - name: ogre_slave1
        type: ethernet
        interface_name: eno1
        master: bond0
        slave_type: bond
      - name: ogre_slave2
        type: ethernet
        interface_name: eno2
        master: bond0
        slave_type: bond
      - name: ogre_slave3
        type: ethernet
        interface_name: eno3
        master: bond0
        slave_type: bond
      - name: ogre_slave4
        type: ethernet
        interface_name: enp65s0f0
        master: bond0
        slave_type: bond
  
  roles:
    - linux-system-roles.network

  tasks:
  - name: network_tuning
    sysctl:
      name: net.core.netdev_budget
      value: "300"
...
