#!/usr/bin/env ansible-playbook
---
- name: omg install
  hosts: all

  tasks:
  - name: Install_pip
    package:
      name: python3-pip

  - name: Omg_pip_install
    pip:
      name: o-must-gather
      state: latest
...
