#!/usr/bin/env ansible-playbook
---
- hosts: rhel_hosts fedora_hosts
  vars:
    Rambox_version: 0.7.7

  tasks:
  - name: RPM_fusion_keys
    rpm_key:
      state: present
      key: "{{ item }}"
    loop:
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    when: ansible_distribution == 'Fedora'

  - name: RPM_fusion_repo
    dnf:
      state: present
      name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    when: ansible_distribution == 'Fedora'

  - name: useful_packages
    yum:
      name:
        - bash-completion
        - pciutils
        - unzip
        - vim
        - wget
        - numactl
        - sos
        - ansible
        - iotop
        - procps-ng
        - net-tools
        - nmap
        - tcpdump
        - traceroute
#        - wireshark - loads X!
        - bind-utils # for dig
        - rsync
#        - ntpdate
        - lsof
#        - libselinux-python # needed for lots of ansible scripts
        - tree
        - dstat
        - iftop
      state: latest

  - name: get_repos
    command:
      cmd: yum repolist --enabled
      warn: false
    register: repolist
    changed_when: false

  - name: packages_if_epel
    yum:
      name:
        - tracer
    when:
    - repolist.stdout.find("epel/x86_64") != -1
    - ansible_distribution == 'RedHat'

  - name: packages_if_fedora
    dnf:
      name:
        - dnf-plugin-system-upgrade
    when: ansible_distribution == 'Fedora'

  - name: copy_top_config
    copy:
      src: toprc
      dest: /root/.toprc

  - name: Rambox_download
    # https://github.com/ramboxapp/community-edition/releases/
    get_url:
      url: https://github.com/ramboxapp/community-edition/releases/download/{{Rambox_version}}/Rambox-{{Rambox_version}}-linux-x86_64.rpm
      dest: /tmp/Rambox-{{Rambox_version}}-linux-x86_64.rpm
    when: "'desktops' in group_names"

  - name: Signal_repo
    command:
      cmd: dnf -y copr enable luminoso/Signal-Desktop
      warn: false
    when:
    - "'desktops' in group_names"
    - repolist.stdout_lines is not search("copr:copr.fedorainfracloud.org:luminoso:Signal-Desktop")

  - name: negativo17_spotify_repo
    command:
      cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-spotify.repo
      warn: false
    when:
    - "'desktops' in group_names"
    - repolist.stdout_lines is not search("negativo17_spotify_repo")

  - name: desktop_packages
    dnf:
      state: latest
      name:
      - network-manager-applet
      - baobab
      - /tmp/Rambox-{{Rambox_version}}-linux-x86_64.rpm
      - signal-desktop
      - hexchat
      - filezilla
      - krb5-auth-dialog
      - krb5-workstation
      - eosrei-emojione-fonts
      - google-android-emoji-fonts
      - google-noto-emoji-color-fonts
      - google-noto-emoji-fonts
      - pavucontrol
      - paprefs
      - spotify-client
    when: "'desktops' in group_names"

- name: vscode
  import_playbook: vscode.yml
  when: "'desktops' in group_names"

- name: git
  import_playbook: git.yml
...
