#!/usr/bin/env ansible-playbook
---
- name: useful packages
  hosts: rhel_hosts fedora_hosts

  tasks:
  - name: RPM_fusion_keys
    rpm_key:
      state: present
      key: "{{ item }}"
    loop:
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    when: ansible_distribution == 'Fedora'

  - name: RPM_fusion_repo
    dnf:
      state: present
      name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    when: ansible_distribution == 'Fedora'

  - name: useful_packages
    yum:
      name:
        - bash-completion
        - pciutils
        - unzip
        - vim
        - wget
        - numactl
        - sos
        - ansible
        - iotop
        - atop
        - procps-ng
        - net-tools
        - nmap
        - tcpdump
        - traceroute
#        - wireshark - loads X!
        - bind-utils # for dig
        - rsync
#        - ntpdate
        - lsof
#        - libselinux-python # needed for lots of ansible scripts
        - tree
        - dstat
        - iftop
        - nethogs
        - rpmconf
        - tracer-common
        - podman
        - buildah
        - skopeo
      state: latest

  - name: tracer_package_dnf
    dnf:
      name:
      - python3-dnf-plugin-tracer
    when: ansible_distribution == 'Fedora' or (ansible_distribution == 'RedHat' and ansible_distribution_major_version >= 8)

  - name: get_repos
    command:
      cmd: yum repolist --enabled
      warn: false
    register: repolist
    changed_when: false

  - name: packages_if_epel
    yum:
      name:
        - tracer
    when:
    - repolist.stdout.find("epel/x86_64") != -1
    - ansible_distribution == 'RedHat'

  - name: packages_if_fedora
    dnf:
      name:
        - dnf-plugin-system-upgrade
    when: ansible_distribution == 'Fedora'

  - name: copy_top_config
    copy:
      src: toprc
      dest: /root/.toprc

  - name: Rambox_latest_version
    uri:
      url: https://api.github.com/repos/ramboxapp/community-edition/releases/latest
      return_content: true
    register: rambox_latest
    when: "'desktops' in group_names"

  - name: Rambox_download
    get_url:
      url: https://github.com/ramboxapp/community-edition/releases/download/{{rambox_latest.json.name}}/Rambox-{{rambox_latest.json.name}}-linux-x86_64.rpm
      dest: /tmp/Rambox-{{rambox_latest.json.name}}-linux-x86_64.rpm
    when: "'desktops' in group_names"

  - name: Signal_repo
    command:
      cmd: dnf -y copr enable luminoso/Signal-Desktop
      warn: false
    when:
    - "'desktops' in group_names"
    - repolist.stdout_lines is not search("copr:copr.fedorainfracloud.org:luminoso:Signal-Desktop")

  - name: negativo17_spotify_repo
    command:
      cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-spotify.repo
      warn: false
    when:
    - "'desktops' in group_names"
    - repolist.stdout_lines is not search("negativo17_spotify_repo")

  - name: desktop_packages
    dnf:
      state: latest
      name:
      - network-manager-applet
      - baobab
      - /tmp/Rambox-{{rambox_latest.json.name}}-linux-x86_64.rpm
      - signal-desktop
      - hexchat
      - filezilla
      - krb5-auth-dialog
      - krb5-workstation
      - eosrei-emojione-fonts
      - google-android-emoji-fonts
      - google-noto-emoji-color-fonts
      - google-noto-emoji-fonts
      # - pavucontrol
      # - paprefs
      - spotify-client
      - gimp
      - rpm-build
      - virt-manager
      - tito # git->rpm packager
      - zoom
      - vlc
      - libreoffice
      - kde-connect
      - virt-viewer
      - youtube-dl
      - java-latest-openjdk
      - "https://go.microsoft.com/fwlink/p/?LinkID=2112907&clcid=0x409&culture=en-us&country=US"
    when: "'desktops' in group_names"

  - name: kdeconnect_firewall
    firewalld:
      service: kdeconnect
      state: enabled
      permanent: yes
      immediate: yes

- name: vscode
  import_playbook: vscode.yml
  when: "'desktops' in group_names"

- name: git
  import_playbook: git.yml

- name: xsos
  import_playbook: xsos.yml
...
