#!/usr/bin/env ansible-playbook
---
- name: useful packages
  hosts: rhel_hosts fedora_hosts

  tasks:
  - name: RPM_fusion_keys
    rpm_key:
      state: present
      key: "{{ item }}"
    loop:
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    when: ansible_distribution == 'Fedora'

  - name: RPM_fusion_repo
    dnf:
      state: present
      name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    when: ansible_distribution == 'Fedora'

  - name: useful_packages
    yum:
      name:
        - bash-completion
        - pciutils
        - unzip
        - vim
        - wget
        - numactl
        - sos
        - iotop
        - procps-ng
        - net-tools
        - nmap
        - tcpdump
        - traceroute
#        - wireshark - loads X!
        - bind-utils # for dig
        - rsync
#        - ntpdate
        - lsof
#        - libselinux-python # needed for lots of ansible scripts
        - tree
        - dstat
        - tracer-common
        - podman
        - buildah
        - skopeo
        - tuned
        - lshw
        - sysstat
        - nmstate
      state: latest

  - name: rhel8_packages
    dnf:
      name:
        - ansible-core
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 8

  - name: pre_rhel8_packages
    dnf:
      name:
        - ansible
        - atop
        - iftop
        - nethogs
        - rpmconf
    when: ansible_distribution == 'Fedora' or (ansible_distribution == 'RedHat' and ansible_distribution_major_version|int < 8)

  - name: tracer_package_dnf
    dnf:
      name:
      - python3-dnf-plugin-tracer
    when: ansible_distribution == 'Fedora'

  - name: get_repos
    command:
      cmd: yum repolist --enabled
    register: repolist
    changed_when: false

  - name: packages_if_epel
    yum:
      name:
        - tracer
    when:
    - repolist.stdout.find("epel/x86_64") != -1
    - ansible_distribution == 'RedHat'

  - name: packages_if_fedora
    dnf:
      name:
        - dnf-plugin-system-upgrade
        - remove-retired-packages
        - rpmfusion-free-release-tainted
        - cpu-x
    when: ansible_distribution == 'Fedora'

  - name: copy_top_config
    copy:
      src: toprc
      dest: /root/.toprc

  - name: signal_repo # https://download.opensuse.org/repositories/network:/im:/signal/Fedora_37/network:im:signal.repo
    yum_repository:
      name: network_im_signal
      description: "Signal Messaging Devel Project (Fedora_37)"
      baseurl: https://download.opensuse.org/repositories/network:/im:/signal/Fedora_$releasever/
      gpgcheck: 1
      gpgkey: https://download.opensuse.org/repositories/network:/im:/signal/Fedora_$releasever/repodata/repomd.xml.key
    when:
    - "'desktops' in group_names"
    - ansible_distribution == 'Fedora'

  - name: desktop_packages
    dnf:
      state: latest
      name:
      - network-manager-applet
      - baobab
      - signal-desktop
      - hexchat
      - filezilla
      - krb5-auth-dialog
      - krb5-workstation
      - eosrei-emojione-fonts
      - google-android-emoji-fonts
      - google-noto-emoji-color-fonts
      - google-noto-emoji-fonts
      # - pavucontrol
      # - paprefs
      - gimp
      - rpm-build
      - virt-manager
      - tito # git->rpm packager
      - zoom
      - vlc
      - libreoffice
      - kde-connect
      - virt-viewer
      - youtube-dl
      - java-latest-openjdk
      - pylint
      - pandoc # convert text formats
      - k3b
      - g++
      - ImageMagick
    when: "'desktops' in group_names"

  - name: kdeconnect_firewall
    firewalld:
      service: kdeconnect
      state: enabled
      permanent: yes
      immediate: yes

- name: webex
  import_playbook: webex.yml
  when: "'desktops' in group_names"

- name: rambox
  import_playbook: rambox.yml
  when: "'desktops' in group_names"

- name: vscode
  import_playbook: vscode.yml
  when: "'desktops' in group_names"

- name: teams
  import_playbook: teams.yml
  when: "'desktops' in group_names"

- name: spotify
  import_playbook: spotify.yml
  when: "'desktops' in group_names"

- name: git
  import_playbook: git.yml

- name: xsos
  import_playbook: xsos.yml
  when: "'servers' not in group_names"

- name: omg
  import_playbook: omg.yml
  when: "'servers' not in group_names"
...
