#!/usr/bin/env ansible-playbook
---
- hosts: rhel_hosts fedora_hosts

  tasks:
  - name: useful_packages
    yum:
      name:
        - bash-completion
        - pciutils
        - unzip
        - vim
        - wget
        - numactl
        - sos
        - ansible
        - iotop
        - procps-ng
        - net-tools
        - nmap
        - tcpdump
        - traceroute
#        - wireshark - loads X!
        - bind-utils # for dig
        - rsync
#        - ntpdate
        - lsof
#        - libselinux-python # needed for lots of ansible scripts
        - tree
        - dstat
        - iftop
      state: latest

  - name: get_repos
    command:
      cmd: yum repolist
      warn: false
    register: repolist
    changed_when: false

  - name: packages_if_epel
    yum:
      name:
        - tracer
    when:
      - repolist.stdout.find("epel/x86_64") != -1
      - ansible_distribution == 'RedHat'

  - name: copy_top_config
    copy:
      src: toprc
      dest: /root/.toprc

- hosts: desktops
  vars:
    Rambox_version: 0.7.7

  tasks:
  - name: Rambox download
    # https://github.com/ramboxapp/community-edition/releases/
    get_url:
      url: https://github.com/ramboxapp/community-edition/releases/download/{{Rambox_version}}/Rambox-{{Rambox_version}}-linux-x86_64.rpm
      dest: /tmp/Rambox-{{Rambox_version}}-linux-x86_64.rpm

  - name: Signal repo
    command:
      cmd: dnf -y copr enable luminoso/Signal-Desktop
      warn: false

  - name: desktop utility
    dnf:
      state: latest
      name:
      - network-manager-applet
      - baobab
      - /tmp/Rambox-{{Rambox_version}}-linux-x86_64.rpm
      - signal-desktop
      - hexchat
      - filezilla

- name: vscode
  import_playbook: vscode.yml
...
