#!/usr/bin/env ansible-playbook
---
- name: Setup_pihole
  hosts: pihole

  # some bits poached from https://github.com/giuaig/ansible-raspi-config/blob/master/raspi-config.yml
  # raspi-config is at https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config

  # card formatting:
  # dd bs=4M if=~pladd/Downloads/2021-01-11-raspios-buster-armhf-lite.img of=/dev/sdb conv=fsync status=progress
  # ENABLE SSH:
  # touch /boot/ssh on card after creating
  # AFTER FIRST BOOT: ssh-copy-id pi@IPADDR

  vars:
    pi_hostname: pihole.home.pladd.net
    memsplit: "16"
    bootbehavior: "B1" # B1 cli, B2 cli autologin, B3 desktop, B4 desktop autologin
    locale: "en_US.UTF-8"
    timezone: "America/New_York"
    ssh_enable: true

    pihole_network: 192.168.42
    net_masklen: 24
    pihole_ip: "{{pihole_network}}.59"
    pihole_cidr: "{{pihole_ip}}/{{net_masklen}}"
    unifi_ip: "{{pihole_network}}.50"
    unifi_cidr: "{{unifi_ip}}/{{net_masklen}}"
    net_router: "{{pihole_network}}.1"
    net_cidr: "{{pihole_network}}.0/{{net_masklen}}"
    net_domain: home.pladd.net

  vars_files:
    - passwords.vault

  tasks:
    - name: Fail_if_vault_not_decrypted
      ansible.builtin.fail:
        msg: "Vault not decrypted"
      when: pihole_webpassword is undefined or pladd_password_hash is undefined

    ###################
    ## PI SETUP
    ###################

    # Setup pladd user
    - name: Pladd_user
      ansible.builtin.include_tasks: user_pladd.yml

    - name: Pladd_sudoer
      ansible.builtin.copy:
        content: "pladd ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/010_pladd-nopasswd
        owner: root
        group: root
        mode: '0440'

    - name: Disable_pi_user
      ansible.builtin.user:
        name: pi
        password: "!"
        shell: /usr/sbin/nologin

    - name: Hostname
      ansible.builtin.hostname:
        name: "{{ pi_hostname }}"
      register: hostname

    - name: Set_Boot_behaviour
      ansible.builtin.shell: "raspi-config nonint do_boot_behaviour {{ bootbehavior }}" # noqa: command-instead-of-shell no-changed-when

    - name: Set_locale
      ansible.builtin.shell: "raspi-config nonint do_change_locale {{ locale }}" # noqa: command-instead-of-shell no-changed-when

    - name: Set_timezone
      community.general.timezone:
        name: "{{ timezone }}"

    # SSH
    - name: Check_if_SSH_enabled
      ansible.builtin.shell: "raspi-config nonint get_ssh" # noqa: command-instead-of-shell
      register: ssh_status
      changed_when: false

    #   debug:
    #     msg: "SSH status is: {{ ssh_status.stdout }}"

    - name: Enable_SSH
      ansible.builtin.shell: "raspi-config nonint do_ssh 0" # noqa: command-instead-of-shell no-changed-when
      when: (ssh_enable) and (ssh_status.stdout != '0')

    # EXPAND FS
    - name: Check_if_FS_is_expandable
      ansible.builtin.shell: "raspi-config nonint get_can_expand" # noqa: command-instead-of-shell
      register: fs_filled
      changed_when: false

    # - ansible.builtin.debug:
    #     msg: "Filesystem is expandable! [{{ fs_filled.stdout }}]"
    #   when: fs_filled.stdout == '1'

    - name: Mark_Filesystem_for_expansion
      ansible.builtin.shell: "raspi-config nonint do_expand_rootfs" # noqa: command-instead-of-shell no-changed-when
      register: expandfs
      when: fs_filled.stdout == '1'

    - name: Inline_Reboot_pihole
      ansible.builtin.reboot:
      when: hostname.changed or expandfs.changed

    - name: Update_apt_package_cache
      ansible.builtin.apt:
        update_cache: true

    - name: Up_to_date
      ansible.builtin.apt:
        name: "*" # noqa: package-latest
        state: latest

    - name: Useful_packages
      ansible.builtin.apt:
        name:
          - bash-completion
          - unzip
          - vim
          - wget
          - iotop
          - htop
          - atop
          - nmap
          - tcpdump
          - traceroute
          - dnsutils # for dig
          - rsync
          - lsof
          - tree
          - dstat
          - chrony # keep accurate time!

    - name: Copy_top_config
      ansible.builtin.copy:
        src: toprc
        dest: /root/.toprc
        mode: u=rw,go=r
        owner: root
        group: root

    ###################
    ###### PIHOLE setup
    ###################
    - name: Pihole_installer
      ansible.builtin.get_url:
        url: https://install.pi-hole.net
        dest: /root/basic-install.sh
        mode: u=rwx,go=x
        owner: root

    - name: Pihole_user
      ansible.builtin.user:
        name: pihole
        group: root
        createhome: false
        shell: /usr/sbin/nologin

    - name: Pihole_directory
      ansible.builtin.file:
        name: /etc/pihole
        state: directory
        mode: u=rwx,go=rx
        owner: pihole
        group: root

    - name: Pihole_setup_file
      ansible.builtin.template:
        src: pihole_setupVars.j2
        dest: /etc/pihole/setupVars.conf
        owner: pihole
        group: root
        backup: true
        mode: u=rw,go=r


    ##### install isn't idempotent - uncomment to run it...
  #  - name: pihole_install
  #    command: /root/basic-install.sh --unattended
  #    register: pihole_install
  #  - name: install_output
  #    debug:
  #      var: pihole_install

    - name: Check_for_updates
      ansible.builtin.shell: pihole -up --check-only # noqa: command-instead-of-shell no-changed-when
      register: pihole_update
      changed_when: false

    - name: Pihole_update
      ansible.builtin.shell: pihole -up  # noqa: command-instead-of-shell no-changed-when
      when: "'Everything is up to date' not in pihole_update.stdout"
      notify: Restart_pihole_service

    # IP ADDRESS
    - name: Set_ip_addresses
      community.general.nmcli:
        state: present
        type: ethernet
        conn_name: eth0
        ifname: eth0
        method4: manual
        ip4:
          - "{{ pihole_cidr }}"
          - "{{ unifi_cidr }}"
        gw4: "{{ net_router }}"
        dns4:
          - "{{ pihole_ip }}"
          - "{{ net_router }}"
          - "8.8.8.8"
        dns4_search:
          - home.pladd.net
          - pladd.net
      notify: Reboot_pihole

  handlers:
    - name: Reboot_pihole
      ansible.builtin.reboot:

    - name: Restart_pihole_service
      ansible.builtin.service:
        name: pihole-FTL
        state: restarted

- import_playbook: static_dns.yml

...
