#!/usr/bin/env ansible-playbook
---
- hosts: pladd-laptop

  tasks:
  - name: install_vpn_packages
    dnf:
      state: latest
      name:
      - https://people.redhat.com/pladd/vpn/redhat-internal-cert-install-0.1-23.el7.csb.noarch.rpm
      - https://people.redhat.com/pladd/vpn/redhat-internal-NetworkManager-openvpn-profiles-non-gnome-0.1-46.el7.csb.noarch.rpm

  # for some reason bootstrap script needs subscription-manager...
  - name: subscription-manager
    dnf:
      name: subscription-manager
      state: latest

  - name: bootstrap_script
    get_url:
      url: https://gitlab.cee.redhat.com/jscarbor/fedora-config/raw/master/bootstrap.sh
      dest: /root/
      mode: a+x

  # - name: run_bootstrap
  #   command: /root/bootstrap.sh

  - name: rhquery_repo
    yum_repository:
      name: rhquery
      description: rhquery tool
      baseurl: http://file.rdu.redhat.com/jhunt/rhquery/fedora/$releasever/noarch/
      gpgcheck: 0

  - name: rhquery_tool
    dnf:
      name: rhquery

  - name: ringcentral_gpg_key
    rpm_key:
      state: present
      key: https://downloads.ringcentral.com/RCM/RC/meetings/linux/LinuxPublicKey.pub

  - name: ringcentral_meetings
    dnf:
      name: https://downloads.ringcentral.com/RCM/RC/meetings/linux/RCMeetingsClientSetup.rpm
      state: latest

  - name: internal_packages
    package:
      name:
      - redhat-internal-libreoffice-templates
      - redhat-internal-libreoffice-red-hat-brand-icons
#      - redhat-internal-redhat-fonts
#      - redhat-internal-we-are-red-hat-week-backgrounds - upgrade pulls in lots of wacky stuff
      # - ringcentral
      - ringcentral-embeddable-voice-app
      - redhat-internal-yubikey
      - redhat-internal-walkme-extension-chrome
      - redhat-internal-smtp-config
      - redhat-internal-cert-install
      - redhat-internal-wireless-config
      - redhat-text-fonts
      - redhat-display-fonts
      - redhat-internal-notosans-fonts
      - redhat-internal-NetworkManager-openvpn-profiles
      - redhat-internal-file-templates
      - redhat-internal-iso-to-usb
      - redhat-internal-backup-config
      - redhat-internal-contact-it-support
      - redhat-internal-libreoffice-extension-convert_text_to_number
      - redhat-internal-libreoffice-extension-vrtnetworkequipment
      - redhat-internal-print-server-selector
      - redhat-internal-software-catalog
      - redhat-internal-wireless-config
      - redhat-internal-ddns-client

      # culled from list pulled in by redhat-internal-software-management
      # redhat-internal-changelog-comms
      # redhat-internal-chat-config
      # redhat-internal-csb-release
      # redhat-internal-dynamic-motd
      # redhat-internal-firefox-config
      # redhat-internal-gnome-config
      # redhat-internal-gnome-shell-extension-lock-keys
      # redhat-internal-infosec-config
      # redhat-internal-luks-change
      # redhat-internal-luks-escrow
      # redhat-internal-network-check
      # redhat-internal-polkit-config
      # redhat-internal-rootpassword
      # redhat-internal-software-catalog
      # redhat-internal-splunkforwarder-config
      # redhat-internal-sssd-config
      # redhat-internal-thunderbird-config
      # redhat-internal-update-notification
      # redhat-internal-walkme-extension-firefox

  - name: ssh_config
    blockinfile:
      path: /home/pladd/.ssh/config
      create: yes
      owner: pladd
      group: pladd
      mode: u=rw,go=-
      block: |
        # Include ~/.ssh/redhat-bastion.config
        #### pladd specific stuff
        Host *.quicklab.*.cee.redhat.com
           User quicklab
           IdentityFile ~/.ssh/quicklab.key
           UserKnownHostsFile /dev/null
           StrictHostKeyChecking no
        Host *.lab.*.cee.redhat.com
           User quicklab
           IdentityFile ~/.ssh/quicklab.key
           UserKnownHostsFile /dev/null
           StrictHostKeyChecking no
        Host *.quicklab.upshift.*.redhat.com
           User quicklab
           IdentityFile ~/.ssh/quicklab.key
           UserKnownHostsFile /dev/null
           StrictHostKeyChecking no
        Host *.lab.upshift.*.redhat.com
           User quicklab
           IdentityFile ~/.ssh/quicklab.key
           UserKnownHostsFile /dev/null
           StrictHostKeyChecking no
        Host *.lab.psi.*.redhat.com
           User quicklab
           IdentityFile ~/.ssh/quicklab.key
           UserKnownHostsFile /dev/null
           StrictHostKeyChecking no
        Host pladd-znc.usersys.redhat.com
          User cloud-user
        Host pvm-hosted-kab.hosts.prod.upshift.rdu2.redhat.com pvm-kabbott-rhel7.hosts.prod.upshift.rdu2.redhat.com kab.usersys.redhat.com tux.usersys.redhat.com
          User karl1

  - name: ssh_include_rh
    get_url:
      url: https://gitlab.corp.redhat.com/it-iam/system-configs/-/raw/master/ssh/fedora-and-rhel-config
      dest: /home/pladd/.ssh/redhat-bastion.config
      mode: u=rw,go=-
      owner: pladd
      group: pladd

  - name: RH_LDAP_config
    blockinfile:
      path: /etc/openldap/ldap.conf
      block: |
        SASL_NOCANON on
        URI ldaps://idm01.iam.prod.int.phx2.redhat.com/ ldaps://idm02.iam.prod.int.phx2.redhat.com/ ldaps://idm01.iam.prod.int.rdu2.redhat.com/ ldaps://idm02.iam.prod.int.rdu2.redhat.com/
        BASE dc=ipa,dc=redhat,dc=com
        TLS_CACERTDIR /etc/openldap/cacerts
        SASL_MECH GSSAPI
        TLS_REQCERT demand
...
