#!/usr/bin/env ansible-playbook
---
- hosts: pladd-laptop

  tasks:
  - name: install_vpn_packages
    dnf:
      state: latest
      name:
      - https://people.redhat.com/pladd/vpn/redhat-internal-cert-install-0.1-23.el7.csb.noarch.rpm
      - https://people.redhat.com/pladd/vpn/redhat-internal-NetworkManager-openvpn-profiles-non-gnome-0.1-46.el7.csb.noarch.rpm

  # for some reason bootstrap script needs subscription-manager...
  - name: subscription-manager
    dnf:
      name: subscription-manager
      state: latest

  - name: bootstrap_script
    get_url:
      url: https://gitlab.cee.redhat.com/jscarbor/fedora-config/raw/master/bootstrap.sh
      dest: /root/
      mode: a+x

  # - name: run_bootstrap
  #   command: /root/bootstrap.sh

  - name: rhquery_repo
    yum_repository:
      name: rhquery
      description: rhquery tool
      baseurl: http://file.rdu.redhat.com/jhunt/rhquery/fedora/$releasever/noarch/
      gpgcheck: 0

  - name: rhquery_tool
    dnf:
      name: rhquery

  - name: ringcentral_gpg_key
    rpm_key:
      state: present
      key: https://downloads.ringcentral.com/RCM/RC/meetings/linux/LinuxPublicKey.pub

  - name: ringcentral_meetings
    dnf:
      name: https://downloads.ringcentral.com/RCM/RC/meetings/linux/RCMeetingsClientSetup.rpm
      state: latest
...
