#!/usr/bin/env ansible-playbook
---
- hosts: pladd-laptop
  vars:
    vpn_packages:
    - redhat-internal-cert-install-0.1-23.el7.csb.noarch.rpm
    - redhat-internal-NetworkManager-openvpn-profiles-non-gnome-0.1-46.el7.csb.noarch.rpm

  tasks:
  - name: download_vpn_packages
    # need updated packages downloaded from https://redhat.service-now.com/help?id=kb_article_view&sysparm_article=KB0005424&sys_kb_id=c8a7b47adb7b4c14def29447db961922
    get_url:
      url: "https://people.redhat.com/pladd/vpn/{{ item }}"
      dest: /tmp/{{ item }}
    loop: "{{ vpn_packages }}"

  - name: install_vpn_packages
    dnf:
      state: latest
      name: /tmp/{{ item }}
    loop: "{{ vpn_packages }}"

  # for some reason bootstrap script needs subscription-manager...
  - name: subscription-manager
    dnf:
      name: subscription-manager
      state: latest

  - name: bootstrap_script
    get_url:
      url: https://gitlab.cee.redhat.com/jscarbor/fedora-config/raw/master/bootstrap.sh
      dest: /root/
      mode: a+x

  - name: run_bootstrap
    command: /root/bootstrap.sh
...
