#!/usr/bin/env ansible-playbook
---
- name: Red Hat Virtualization Manager
  hosts: rhv_manager_hosts
  vars_files:
    - passwords.vault

  tasks:
  - name: RHV_manager_repositories
    rhsm_repository:
      name:
        - rhel-7-server-rhv-4.3-manager-rpms
        - rhel-7-server-rhv-4-manager-tools-rpms
        - rhel-7-server-ansible-2-rpms
        - jb-eap-7.2-for-rhel-7-server-rpms
      state: enabled

  - name: rhv_manager_packages
    yum:
      name: rhvm

  - name: fail if vault not decrypted
    fail: msg="Vault not decrypted"
    when: rhv_admin_pw is undefined

  - name: answer_file
    template:
      src: rhv/rhv_answerfile.j2
      dest: /root/rhv_answerfile.conf
      backup: true
      mode: u=rw,go-rwx
      owner: root
      group: root

  # *** Didn't fully work, had to run manually ***
  # - name: engine_setup
  #   command:
  #     argv:
  #       - engine-setup
  #       - "--config=/root/rhv_answerfile.conf"
  #       - "--log=/root/rhv_engine-setup.log"
  #       - "--accept-defaults"
  #     stdin: /dev/null

- name: Red Hat Virtualization Hosts
  hosts: rhv_hosts

  tasks:
  - name: RHV_host_repositories
    rhsm_repository:
      name:
        - rhel-7-server-ansible-2-rpms
        - rhel-7-server-rhv-4-mgmt-agent-rpms
      state: enabled

# use?: ansible-galaxy install oVirt.ovirt-ansible-roles

# get this key from "Compute->Hosts->New authentication section - haven't found the API for this yet..."
  - name: host_key
    authorized_key:
      user: root
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkWTTz7pn6fjvNYx9TSWtEw++qIYKP6Jhq4f5nehOxMSCl9BYdP8qLug/Y1yMcPPDebEyeXGeT+pyf4R5b1+kRCh/fMHCBZMcxD4BRZtbv8KT8VSrkYiZcsOJH9SOTL5gScbGV1lZVYZAFbZjfmgpvtm4VJXikPY4lv/Xtl2xbIv48AdwvYBWPIao5Kbm6+S032jhKYElJeUUTumSqDD0Nxf+Zx50jnocEgDOGpj00FdmtQD9AZ+x/yETaaxbjIBd0K8k5yMNosxnrr6aCpsvXV9qFT/bcqZ+8VQkBgAsigIo48TPqDlMDivNKQ1C71necxflfZ0uDlKIn40g85GNh ovirt-engine"

# add host via the host dashboard...
  - name: storage_permissions
    file:
      owner: vdsm
      group: kvm
      mode: 0755
      path: /rhv_data
      state: directory

# new storage domain: local on host

# turn off session timeouts
  - name: check_session_timeout
    command: engine-config -g UserSessionTimeOutInterval
    register: session_timeout
    changed_when: false

  - name: disable_session_timeout
    command: engine-config -s UserSessionTimeOutInterval=-1
    notify: restart_ovirt_engine
    when: "'-1' not in session_timeout.stdout"

  handlers:
  - name: restart_ovirt_engine
    service:
      name: ovirt-engine
      state: restarted

...