#!/usr/bin/env ansible-playbook
---
- name: Red Hat Virtualization Manager
  hosts: rhv_manager_hosts
  vars_files:
    - passwords.vault

  tasks:
  - name: RHV_manager_repositories
    rhsm_repository:
      name:
        - rhel-7-server-rhv-4.3-manager-rpms
        - rhel-7-server-rhv-4-manager-tools-rpms
        - rhel-7-server-ansible-2-rpms
        - jb-eap-7.2-for-rhel-7-server-rpms
      state: enabled

  - name: rhv_manager_packages
    yum:
      name: rhvm

  - name: fail if vault not decrypted
    fail: msg="Vault not decrypted"
    when: subscription_manager_id is undefined or subscription_manager_pw is undefined

  - name: answer_file
    template:
      src: rhv/rhv_answerfile.j2
      dest: /root/rhv_answerfile.conf
      backup: true
      mode: u=rw,go-rwx
      owner: root
      group: root

  # *** Didn't fully work, had to run manually ***
  # - name: engine_setup
  #   command:
  #     argv:
  #       - engine-setup
  #       - "--config=/root/rhv_answerfile.conf"
  #       - "--log=/root/rhv_engine-setup.log"
  #       - "--accept-defaults"
  #     stdin: /dev/null

- name: Red Hat Virtualization Hosts
  hosts: rhv_hosts

  tasks:
  - name: RHV_host_repositories
    rhsm_repository:
      name:
        - rhel-7-server-ansible-2-rpms
        - rhel-7-server-rhv-4-mgmt-agent-rpms
      state: enabled

...
