#!/usr/bin/env ansible-playbook
---
- name: setup_rhv_guests
  hosts: rhv_guests
  vars:
    repositories_for_rhel_version:
      "6":
      - rhel-6-server-rhv-4-agent-rpms
      "7":
      - rhel-7-server-rh-common-rpms
      "8":
      - rhel-8-for-x86_64-appstream-rpms

  tasks:
  - name: repositories
    rhsm_repository:
      name: "{{ repositories_for_rhel_version[ansible_distribution_major_version] }}"
      state: enabled

  - name: rhv_packages_rhel6-7
    yum:
      name:
      - ovirt-guest-agent-common
      state: latest
    when: ansible_distribution_major_version in [6,7]

  - name: rhv_packages_rhel8
    yum:
      name:
      - qemu-guest-agent
      state: latest
    when: ansible_distribution_major_version in [8]

  - name: guest_agent_started
    service:
      name: "{{ 'qemu-ga' if ansible_distribution_major_version == 6 else 'qemu-guest-agent'  }}"
      state: started
      enabled: true

...
