#!/usr/bin/env ansible-playbook
---
- name: SSH_config
  hosts: pladd-laptop

  tasks:
  - name: Disable_sshd.service
    service:
      name: sshd.service
      state: stopped
      enabled: false

  - name: Enable_sshd.socket
    service:
      name: sshd.socket
      state: started
      enabled: true

  - name: Ssh_config
    blockinfile:
      path: /home/pladd/.ssh/config
      create: true
      owner: pladd
      group: pladd
      mode: u=rw,go=-
      block: |
        Host github.com
          HostName github.com
          User laddp
          IdentityFile ~/.ssh/id_rsa

        Host iad2
          HostName bastion-iad2.corp.redhat.com
          ProxyCommand none
          GSSAPIAuthentication yes
          User pladd

        Host people.stage.redhat.com
          User pladd
          ProxyJump iad2

        Host people.redhat.com
          User pladd
          ProxyJump iad2
