#!/usr/bin/env ansible-playbook
---
- name: systemd-resolve setup for home
  hosts: pladd-laptop


  tasks:
  - name: debug
    blockinfile:
      path: /etc/systemd/system/systemd-resolved.service.d/override.conf
      create: yes
      block: |
        [Service]
        Environment=SYSTEMD_LOG_LEVEL=debug
    notify:
      - restart resolved

  # - name: resolved-resolve-libvirt
  #   blockinfile:
  #     dest: /etc/systemd/resolved.conf.d/libvirt_resolve.conf
  #     create: yes
  #     block: |
  #       [Resolve]
  #       DNS=192.168.122.1%virbr0
  #   notify:
  #     - restart resolved

  handlers:
  - name: restart resolved
    systemd:
      name: systemd-resolved
      state: restarted
      daemon_reload: yes
...
