#!/usr/bin/env ansible-playbook
---
- name: MS_Teams_install
  hosts: desktops
  tasks:

  - name: MS_repos
    dnf:
      name: https://packages.microsoft.com/fedora/41/prod/Packages/p/packages-microsoft-prod-1.1-1.noarch.rpm
    when: ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

  - name: package
    package:
      name: teams
      state: latest

...
