#!/usr/bin/env ansible-playbook
---
- name: Configure unifi
  hosts: pihole
  vars_files:
    - passwords.vault
  vars:
    ansible_become_pass: "{{ unifi_sudo_pass }}"

  tasks:

    # tasks from https://help.ui.com/hc/en-us/articles/220066768-Updating-and-Installing-Self-Hosted-UniFi-Network-Servers-Linux
    - name: Python_module_prereq # needed for deb822_repository module
      ansible.builtin.apt:
        pkg: python3-debian

    - name: Unifi_reposotory
      ansible.builtin.deb822_repository:
        name: unifi
        architectures: amd64,arm64
        uris: https://www.ui.com/downloads/unifi/debian
        suites: stable
        components: ubiquiti
        signed_by: https://dl.ui.com/unifi/unifi-repo.gpg

    # - name: MongoDB_repository # not working - no Debian arm64 binaries for mongodb-org
    #   ansible.builtin.deb822_repository:
    #     name: mongodb
    #     architectures: amd64,arm64
    #     uris: https://repo.mongodb.org/apt/debian
    #     suites: bookworm/mongodb-org/8.2
    #     components: main
    #     signed_by: https://www.mongodb.org/static/pgp/server-8.0.asc

    - name: MongoDB_repository
      ansible.builtin.deb822_repository:
        name: mongodb
        architectures: amd64,arm64
        uris: https://repo.mongodb.org/apt/ubuntu
        suites: jammy/mongodb-org/8.0  # 8.2 is not supported for Unifi yet
        components: multiverse
        signed_by: https://www.mongodb.org/static/pgp/server-8.0.asc

    - name: Install_Unifi_and_dependencies
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - apt-transport-https
          - mongodb-org
          - unifi
        update_cache: yes
...
