#!/usr/bin/env ansible-playbook
---
- name: Create Ubiquiti management VM
  hosts: beast
  vars:
    ubvm:
    - name: ubiquiti
      memory: 4
      memory_units: G
      vcpu: 8
      disks:
      - name: ubiquiti
        path: /var/lib/libvirt/images
        disk_driver: virtio
        format: qcow2
      network_interfaces:
      - type: direct
        source: enp65s1
        mode: bridge

  tasks:
  - name: store template file for testing
    template:
      dest: /root/ubiquiti.xml
      src: vm_template.xml.j2
    with_items: "{{ ubvm }}"

  - name: define vm from xml and set autostart
    virt:
      command: define
      xml: "{{ lookup('template', 'vm_template.xml.j2') }}"
      autostart: yes
    with_items: "{{ ubvm }}"

  - name: start VM
    virt:
      state: running
      name: ubiquiti

- name: Configure unifi
  hosts: unifi
  vars_files:
    - passwords.vault
  vars:
    - ansible_become_pass: "{{ unifi_sudo_pass }}"

  tasks:
  - name: package_source
    copy:
      dest: /etc/apt/sources.list.d/100-ubnt-unifi.list
      content: "deb https://www.ui.com/downloads/unifi/debian stable ubiquiti"

  - name: package_up_to_date
    apt:
      name:
        - unifi
      state: latest
...
