#!/usr/bin/env ansible-playbook
---
- name: Update all existing packages
  hosts: all
  vars_files:
  - unifi.vault

  tasks:
  - name: yum_systems_up_to_date
    yum:
      name:  '*'
      state: latest
    when:
    - ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

  - name: apt_systems_up_to_date
    apt:
      name: "*"
      state: latest
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: firmware_updates
    command: "fwupdmgr refresh; fwupdmgr update -y"
    register: fwupdmgr
    when: inventory_hostname == 'pladd-laptop'

  - name: fwupdmgr_output
    debug:
      var: fwupdmgr.stdout_lines
    when: inventory_hostname == 'pladd-laptop'

...
