#!/usr/bin/env ansible-playbook
---
- name: Update all existing packages
  hosts: all
  vars_files:
  - unifi.vault

  tasks:
  - name: yum_systems_up_to_date
    yum:
      name:  '*'
      state: latest
    when:
    - ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

  - name: apt_systems_up_to_date
    apt:
      name: "*"
      state: latest
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

...
