#!/usr/bin/env ansible-playbook
---
- name: Update all existing packages
  hosts: all
  vars_files:
    - unifi.vault

  tasks:
    - name: Yum_systems_up_to_date
      ansible.builtin.yum:
        state: latest
      when:
        - ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

    - name: Apt_systems_up_to_date
      ansible.builtin.apt:
        state: latest
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: pihole_update
      command: pihole -up
      register: pihole_update
      when: inventory_hostname == 'pihole'

    - name: update_output
      debug:
        var: pihole_update
      when: inventory_hostname == 'pihole'

    - name: Firmware_update_refresh
      ansible.builtin.command: "fwupdmgr refresh"
      register: fwrefresh
      when: inventory_hostname == 'pladd-laptop'
      failed_when: fwrefresh.rc == 1 or fwrefresh.rc > 2

    - name: Firmware_update
      ansible.builtin.command: "fwupdmgr update -y"
      register: fwupdmgr
      when: inventory_hostname == 'pladd-laptop'
      changed_when: "'Idle' not in fwrefresh.stderr"

    - name: Fwupdmgr_output
      ansible.builtin.debug:
        var: fwupdmgr.stderr
      when:
        - inventory_hostname == 'pladd-laptop'
        - "'Idle' not in fwrefresh.stderr"


- name: Flatpaks
  import_playbook: flatpak.yml
  when: "'desktops' in group_names"

...
