#!/usr/bin/env ansible-playbook
---
- hosts: all
  vars_files:
    - passwords.vault

  tasks:
  - name: fail if vault not decrypted
    fail: msg="Vault not decrypted"
    when: pladd_password_hash is undefined

  - include_tasks: user_pladd.yml
...