#!/usr/bin/env ansible-playbook
---
- hosts: all

  tasks:
  - name: add_Patrick
    user:
      name: pladd
      comment: "Patrick Ladd"

  - name: ssh_key
    authorized_key:
      user: pladd
      key: "{{ item }}"
    with_file:
      - /home/pladd/.ssh/id_rsa.pub
...