#!/usr/bin/env ansible-playbook
---
- name: vscode install
  hosts: desktops
  tasks:

  - name: vscode_repo
    yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    when: ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

  - name: package
    package:
      name: code
      state: latest

...
